name: Build and Release Android App

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        # Only run npm install if the cache was not restored
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm install

      - name: Build Android App (AAB)

        run: |
          cd android
          ./gradlew bundleRelease

      - name: Get App Version
        # This step only runs if the trigger was a tag
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: "Release v${{ env.APP_VERSION }}"
          body: "Release version ${{ env.APP_VERSION }} of the Stream app."
          draft: false
          prerelease: false

      - name: Upload Release Asset (AAB)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./android/app/build/outputs/bundle/release/app-release.aab
          asset_name: stream-v${{ env.APP_VERSION }}.aab
          asset_content_type: application/vnd.android.package-archive
